FlatFilers/flatfile-plugins

.changeset/seven-owls-tickle.md, pnpm-lock.yaml
Fix `pnpm-lock.yaml` to reference latest `@flatfile/api`
=> chore: fix lockfile and major changeset

.changeset/polite-points-dress.md, plugins/record-hook/src/RecordHook.ts
Here are 2 examples (mind the capitalization 😅):
In the `RecordHook` export:
```ts
await RecordHook(event, async (record: FlatfileRecord, event: FlatfileEvent) => {
...
})
```
In the `recordHook` plugin:
```ts
listener.use(
recordHook('sheetSlug', async (record: FlatfileRecord, event: FlatfileEvent) => {
...
})
)
```
=> feat: add event to RecordHook handler()

.changeset/grumpy-dryers-switch.md, plugins/dxp-configure/src/index.ts, plugins/dxp-configure/src/shim.target.spec.ts, plugins/dxp-configure/src/shim.target.ts, pnpm-lock.yaml
Moves target shim to the dxpConfigure shim. It currently lives on the polling listener but should be on the shim instead to be portable across event routers:
https://github.com/FlatFilers/platform-sdk-mono/blob/main/packages/cli/src/shared/utils/polling.ts#L6-L20
=> chore: dxp target shim

.changeset/cold-houses-relate.md, plugins/record-hook/src/index.ts, plugins/record-hook/src/record.hook.plugin.ts
Adds export of `FlatfileRecord` and change plugin name
Changes name of the `recordHook` plugin to `recordHookPlugin` (with the fallback of `recordHook` for backwards compatibility)
=> feat: export FlatfileRecord from RecordHookPlugin

.changeset/unlucky-peas-sit.md, package-lock.json, plugins/psv-extractor/src/psv.extractor.ts
To handle empty cells, you can modify the papaparse configuration by setting the skipEmptyLines option to 'greedy'. This option tells papaparse to treat lines with missing values as if they contain empty values.
=> Accept empty cells for psv

.changeset/swift-rivers-whisper.md, plugins/record-hook/src/RecordHook.ts, plugins/record-hook/src/async.batch.spec.ts, plugins/record-hook/src/async.batch.ts, plugins/record-hook/src/record.hook.e2e.spec.ts, plugins/record-hook/src/record.hook.plugin.ts
The `bulkRecordHook` function passes batches of records to the given `handler`.
Install:
```
npm i @flatfile/plugin-record-hook @flatfile/hooks
```
Default chunk size is 1,000 (same as commit:created)
Default parallel is 1. These will run in parallel.
Example usage:
```
import { FlatfileRecord } from '@flatfile/hooks'
import { bulkRecordHook } from '@flatfile/plugin-record-hook'
export default async function (listener) {
listener.use(
bulkRecordHook(
'contacts',
(records: FlatfileRecord[]) => {
return records.map((r) => {
const email = r.get('email') as string
if (!email) {
console.log('Email is required')
r.addError('email', 'Email is required')
}
const validEmailAddress = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
if (email !== null && !validEmailAddress.test(email)) {
console.log('Invalid email …
```
=> feat: bulk record hook

package-lock.json, package.json, plugins/automap/package.json, plugins/delimiter-extractor/package.json, plugins/dxp-configure/package.json, plugins/export-worbook/package.json, plugins/json-extractor/package.json, plugins/psv-extractor/package.json, plugins/record-hook/package.json, plugins/tsv-extractor/package.json, plugins/xlsx-extractor/package.json, plugins/xml-extractor/package.json, plugins/zip-extractor/package.json, support/common-utils/package.json, utils/common/package.json, utils/extractor/package.json, utils/file-buffer/package.json
The following changes should fix the "flakiness" of the monorepo in CI.
- Update out-of-sync deps (published versions w/ what is in the lock file)
-  `@flatfile/plugin-delimiter-extractor`
- `@flatfile/util-extractor`
- `@flatfile/json-extractor`
- `@flatfile/util-common`
- `@flatfile/plugin-record-hook`
- `@flatfile/plugin-xlsx-extractor`
- Force Turbo (`--concurrency=1`) and Jest (`--runInBand`) to run tests sequentially so they don't step on top of each other 
Note: this is a temporary fix and long term we should look at the Turbo cache configuration
=> monorepo fixes

.changeset/perfect-pens-shake.md, plugins/autocast/package.json, plugins/delimiter-extractor/src/parser.spec.ts, plugins/json-extractor/src/parser.spec.ts, plugins/psv-extractor/src/index.ts, plugins/tsv-extractor/src/index.ts
This PR does a couple things:
- Removes the `hasHeader` parameter from the PSV & TSV extractors. This parameter was introduced in https://github.com/FlatFilers/flatfile-plugins/pull/150 and replaced with header row auto-detection in https://github.com/FlatFilers/flatfile-plugins/pull/158.
- Fixes a typo in the `autocast/package.json`.
- Changes test descriptions to better describe the purpose.
=> chore: cleanup

.changeset/brown-buckets-drum.md, package-lock.json, plugins/xml-extractor/package.json, plugins/xml-extractor/src/index.ts, plugins/xml-extractor/src/parser.spec.ts, plugins/xml-extractor/src/parser.ts
This PR refactors the `XMLExtractor` to use the `@flatfile/util-extractor` package. Using the utility extractor package resolves a job completion bug in the XMLExtractor and increases the maintainability of package code through DRYing.
=> feat:refactor XMLExtractor to use `@flatfile/util-extractor` package

.changeset/gorgeous-rules-end.md, package-lock.json, plugins/delimiter-extractor/README.md, plugins/xlsx-extractor/README.md, plugins/xml-extractor/package.json, plugins/xml-extractor/src/parser.spec.ts, plugins/xml-extractor/src/parser.ts
Fixes bug introduced in https://github.com/FlatFilers/flatfile-plugins/pull/172 where values were not being pass in object. This PR also adds a test for `parseBuffer()`
Previous:
```
data: [
{
firstName: 'Tony',
lastName: 'Lamb',
email: 'me@opbaj.tp',
},
]
```
Fixed:
```
data: [
{
firstName: { value: 'Tony' },
lastName: { value: 'Lamb' },
email: { value: 'me@opbaj.tp' },
},
]
```
=> fix:XMLExtractor parser

.changeset/sweet-spoons-camp.md, package-lock.json, plugins/zip-extractor/src/index.ts
This PR excludes the `__MACOSX` directory from being uploaded to Flatfile. Fixes #177.
=> fix: exclude unwanted dir

.changeset/eighty-kiwis-cry.md, package-lock.json, plugins/pdf-extractor/CHANGELOG.md, plugins/pdf-extractor/README.md, plugins/pdf-extractor/package.json, plugins/pdf-extractor/src/index.ts, plugins/pdf-extractor/src/plugin.ts
PDF extractor plugin that uses `pdftables.com` to handle PDF -> CSV conversion for upload to FF. [API](https://pdftables.com/pdf-to-excel-api) uses a blank row between pages. Customers are required to pay for the service themselves. 
https://www.loom.com/share/08744b5b94fd433789b4b115927ca22d?sid=4f844831-4d05-4825-b969-224d7228397e
```ts
import { pdfExtractorPlugin } from "@flatfile/plugin-pdf-extractor";
export default function (listener: FlatfileListener) {
listener.use(pdfExtractorPlugin({ apiKey: "key" }));
}
```
=> feat: pdf extractor plugin

.changeset/brave-toes-fly.md, utils/file-buffer/src/index.ts
**Issue** 
Exporting a workbook fires a `file:created` event. If an Extractor plugins is active, it picks up the `file:created` event and proceeds to extract it.
```
import { exportWorkbookPlugin } from '@flatfile/plugin-export-worbook'
import { ExcelExtractor } from '@flatfile/plugin-xlsx-extractor'
export default function (listener) {
listener.use(exportWorkbookPlugin())
listener.use(ExcelExtractor())
}
```
**Solution** 
This PR adds a check to the fileBuffer to check the `file.mode`. If `file.mode === 'export'` the fileBuffer will ignore the event.
=> fix: exclude exported files from fileBuffer

.changeset/metal-spoons-give.md, package-lock.json, package.json, plugins/automap/package.json, plugins/delimiter-extractor/package.json, plugins/dxp-configure/package.json, plugins/job-handler/README.md, plugins/job-handler/package.json, plugins/job-handler/src/index.ts, plugins/job-handler/src/job.handler.spec.ts, plugins/job-handler/src/job.handler.ts, plugins/json-extractor/package.json, plugins/record-hook/package.json, plugins/space-configure/README.md, plugins/space-configure/package.json, plugins/space-configure/ref/getting_started.ts, plugins/space-configure/src/index.ts, plugins/space-configure/src/space.configure.spec.ts, plugins/space-configure/src/space.configure.ts, plugins/zip-extractor/package.json, tsconfig.json, utils/common/src/index.ts, utils/common/src/logging.helper.spec.ts, utils/common/src/logging.helper.ts, utils/extractor/package.json, utils/testing/src/test.helpers.ts, utils/testing/src/test.listener.ts
This PR introduces two new plugins: `@flatfile/plugin-job-handler` and `@flatfile/plugin-space-configure`.
Docs ref: https://github.com/FlatFilers/Guides/pull/731
=> feat: job handler & space configure plugins

.changeset/selfish-gorillas-clap.md, plugins/delimiter-extractor/src/index.ts, plugins/json-extractor/src/index.ts, plugins/psv-extractor/src/index.ts, plugins/tsv-extractor/src/index.ts, plugins/xlsx-extractor/src/index.ts, plugins/xml-extractor/src/index.ts, utils/common/src/async.batch.ts, utils/extractor/src/index.ts
Guide PR: https://github.com/FlatFilers/Guides/pull/735
This PR adds the ability to configure batching options: `chunkSize` by default has a value of `1000`, `parallel` by default has a value of `1`. These can now be changed like so:
```
export default function (listener: FlatfileListener) {
listener.use(JSONExtractor({ chunkSize: 100, parallel: 2 }))
listener.use(ExcelExtractor({ chunkSize: 200, parallel: 2 }))
listener.use(XMLExtractor({ chunkSize: 300, parallel: 2 }))
listener.use(PSVExtractor({ chunkSize: 400, parallel: 2 }))
listener.use(TSVExtractor({ chunkSize: 500, parallel: 2 }))
listener.use(
DelimiterExtractor('txt', { delimiter: '~', chunkSize: 600, parallel: 2 })
)
listener.use(
DelimiterExtractor('semicolin', {
delimiter: ';',
chunkSize: 700,
parallel: 2,
})
)
}
```
=> feat: add configurable batch options

.changeset/light-emus-rescue.md, package-lock.json, plugins/autocast/package.json, plugins/autocast/src/autocast.plugin.ts
This PR introduces an optional `fieldFilter`, and enables filtering by either `sheetId` or `sheetSlug`.
Example:
```
listener.use(autocast({ sheetId: 'us_sh_12345678' }))
listener.use(autocast({ sheetSlug: 'foo' }, ['numberField']))
listener.use(autocast({ sheetId: 'us_sh_12345678' }, ['numberField']))
listener.use(autocast({ sheetSlug: 'bar' }, ['numberField', 'dateField']))
```
=> feat: add field filter & replace sheetId with sheetSlug

.changeset/warm-cherries-help.md, plugins/autocast/src/autocast.plugin.ts
This PR requires a `sheetSlug` for filtering sheets. 
Guides update: https://github.com/FlatFilers/Guides/pull/753
=> Remove sheetId filtering

.changeset/cool-gifts-push.md, package-lock.json, plugins/autocast/src/autocast.plugin.spec.ts, plugins/autocast/src/autocast.plugin.ts
This PR resolves an issue with date casting.
=> Fix date bug

.changeset/silver-ants-juggle.md, package-lock.json, plugins/autocast/package.json, plugins/automap/package.json, plugins/dedupe/package.json, plugins/delimiter-extractor/package.json, plugins/dxp-configure/package.json, plugins/export-worbook/package.json, plugins/job-handler/package.json, plugins/json-extractor/package.json, plugins/pdf-extractor/package.json, plugins/psv-extractor/package.json, plugins/record-hook/package.json, plugins/space-configure/package.json, plugins/tsv-extractor/package.json, plugins/webhook-egress/package.json, plugins/xlsx-extractor/package.json, plugins/xml-extractor/package.json, plugins/zip-extractor/package.json, utils/extractor/package.json, utils/file-buffer/package.json, utils/response-rejection/package.json, utils/testing/package.json
This PR updates the `@flatfile/api` dependency version to the latest release on all plugins.
=> chore: update @flatfile/api dependency version

.changeset/many-camels-tease.md, package-lock.json, plugins/space-configure/src/space.configure.ts
This PR allows spaces to be configured without providing workbooks.
Simplistic usage:
```
listener.use(
configureSpace({
workbooks: [],
})
)
```
=> feat: support configuring spaces w/o workbooks

.changeset/calm-forks-lick.md, package-lock.json, plugins/autocast/package.json, plugins/automap/package.json, plugins/dedupe/package.json, plugins/delimiter-extractor/package.json, plugins/dxp-configure/package.json, plugins/export-worbook/package.json, plugins/job-handler/package.json, plugins/json-extractor/package.json, plugins/merge-connection/package.json, plugins/merge-connection/src/index.ts, plugins/pdf-extractor/package.json, plugins/psv-extractor/package.json, plugins/record-hook/package.json, plugins/space-configure/package.json, plugins/tsv-extractor/package.json, plugins/webhook-egress/package.json, plugins/xlsx-extractor/package.json, plugins/xml-extractor/package.json, plugins/zip-extractor/package.json, utils/extractor/package.json, utils/extractor/src/index.ts, utils/file-buffer/package.json, utils/response-rejection/package.json, utils/testing/package.json
This PR updates the `@flatfile/api` dependency across all plugins. Calls to `api.records.insert()` set the `compressRequestBody` option to `true` to increase insertion speed.
=> chore: update dependencies

.changeset/thin-dodos-jog.md, package-lock.json, plugins/automap/src/automap.service.ts
Prior to this PR, the Automap plugin would match the provided `defaultTargetSheet` to the `sheet.name` or `sheet.id`. This PR includes matching the `defaultTargetSheet` to the `sheet.slug`.
Also remove pause icon to give better support for multiple automap listeners:
Guide PR: https://github.com/FlatFilers/Guides/pull/858
Closes: https://github.com/FlatFilers/support-triage/issues/697
=> feat: automap match on sheet slug

.changeset/serious-cherries-hang.md, package-lock.json, plugins/automap/src/automap.service.ts
Issue:
If the "import" process is started (either by dropping a file into a sheet or by clicking the "Import" button from a file), a secondary `workbook:map` job is created, which was being picked up by the automap plugin and resulted in duplicate entries in a sheet.
Solution:
This PR adds a `isAutomap` flag to the job's `input` to allow the automap plugin to filter on. If the flag isn't provided automap will just return.
Closes: https://github.com/FlatFilers/support-triage/issues/708
=> feat: ignore mapping jobs not created by automap plugin

.changeset/sweet-bears-jump.md, plugins/xlsx-extractor/src/index.ts, plugins/xlsx-extractor/src/parser.ts
This PR exposes SheetJS's `raw` option to the `ExcelExtractor`. This option allows preserving formatted text by default. If `raw` is set to true, it will return the raw value.
Guide PR: https://github.com/FlatFilers/Guides/pull/874
=> feat: add raw option to Excel extractor

.changeset/few-suits-rule.md, plugins/export-workbook/src/plugin.ts
Added a "next" action in the job completion response that redirects users to the "Available Downloads" section of the Files page in Flatfile.
This enhancement provides a smoother user experience by guiding users directly to their exported files.
=> Add "next" URL to job completion response

.changeset/angry-ears-boil.md, package-lock.json, utils/common/package.json, utils/common/src/index.ts, utils/common/src/process.records.ts
This PR introduces a utility for applying a callback on all records in a sheet.
Plugins to update:
=> feat:process-records-utility

.changeset/bright-numbers-guess.md, package-lock.json, plugins/record-hook/package.json
This PR updates the `@flatfile/api` dependency to the latest (1.5.33) version.
=> chore: recordHook dep update

.changeset/afraid-melons-sniff.md, package-lock.json, plugins/record-hook/src/RecordHook.ts
This PR fixes an issue caused by trying to complete a commit when the `trackChanges` flag is disabled on the Workbook.
Fixes: https://github.com/FlatFilers/support-triage/issues/748
=> fix: check trackChanges flag before completing commit

.changeset/cyan-parents-worry.md, package-lock.json, plugins/record-hook/src/RecordHook.ts
This PR introduces deep comparison of the original record with the presumably modified record to accurately send only patches for updated records.
Fixes: https://github.com/FlatFilers/support-triage/issues/739
=> fix: recordHook deep comparison of modified Records

.changeset/swift-socks-joke.md, package-lock.json, plugins/dedupe/src/plugin.ts
This PR fixes a bug by completing the job when no duplicate values are found. Closes https://github.com/FlatFilers/support-triage/issues/743
=> fix: bug fix when no duplicate values found

.changeset/small-maps-lie.md, utils/common/src/process.records.ts
This PR adds a small upgrade to the processRecords() to let the callback() return records or void.
=> feat: allow returning void from callback

.changeset/nice-peas-yell.md, plugins/job-handler/src/job.handler.ts
closes https://github.com/FlatFilers/support-triage/issues/796
Changes the jobHandler to set `acknowledge:true` in the job outcome used in the catch block, so that errors show up in a Modal instead of a Toast. This fixes a problem where `space:configure` jobs finish faster than the space can load to see a job event that would trigger a Toast.
=> fix: show a modal instead of a toast when jobHandler catches an error

.changeset/spotty-months-own.md, package-lock.json, plugins/xlsx-extractor/src/header.detection.ts, plugins/xlsx-extractor/src/index.ts, plugins/xlsx-extractor/src/parser.spec.ts, plugins/xlsx-extractor/src/parser.ts, utils/extractor/src/index.ts
This PR introduces new header detection options.
Guide: https://github.com/FlatFilers/Guides/pull/962
Usage:
```
// default
listener.use(
ExcelExtractor()
)
// or...
listener.use(
ExcelExtractor({
headerDetectionOptions: {
algorithm: 'default',
rowsToSearch: 30, // Default is 10
},
})
)
// explicitHeaders
listener.use(
ExcelExtractor({
headerDetectionOptions: {
algorithm: 'explicitHeaders',
headers: ['fiRsT NamE', 'LaSt nAme', 'emAil'],
},
})
)
// specificRows
listener.use(
ExcelExtractor({
headerDetectionOptions: {
algorithm: 'specificRows',
rowNumbers: [2], // 0 based
},
})
)
```
=> feat: update header detection logic

.changeset/cyan-ligers-teach.md, package-lock.json, plugins/xlsx-extractor/src/header.detection.ts, plugins/xlsx-extractor/src/parser.ts, utils/extractor/src/index.ts
This PR fixes extraction failure when an xlsx file contains empty sheets. Additionally it enables [`dense` mode](https://docs.sheetjs.com/docs/demos/bigdata/stream/#dense-mode) for improved memory usage when extracting an exceptionally large file.
Test file: [Book1.xlsx](https://github.com/FlatFilers/flatfile-plugins/files/13618616/Book1.xlsx)
```
// One xlsx sheet will be extracted
listener.use(ExcelExtractor())
// Two xlsx sheets will be extracted
listener.use(
ExcelExtractor({
headerDetectionOptions: {
algorithm: 'explicitHeaders',
headers: ['One', 'Two', 'Three'],
},
})
)
```
Closes: https://github.com/FlatFilers/flatfile-plugins/issues/200 & https://github.com/FlatFilers/support-triage/issues/821 & https://github.com/FlatFilers/support-triage/issues/839
=> feat: handle empty sheets & enable dense mode for improved memory usage

.changeset/sweet-peaches-dream.md, package-lock.json, plugins/export-workbook/package.json, plugins/export-workbook/src/plugin.ts, utils/common/src/process.records.ts
This PR refactors the export-workbook plugin and fixes a bug when multiple comments exist on a cell by threading them.
**Closes:** https://github.com/FlatFilers/support-triage/issues/814
=> feat: refactor export-workbook plugin

.changeset/plenty-brooms-scream.md, package-lock.json, plugins/record-hook/package.json, plugins/record-hook/src/RecordHook.ts
This PR replaces the effect library in favor of custom concurrency control in recordHook. No new functionality.
=> feat: replace effect library

.changeset/unlucky-bugs-unite.md, plugins/automap/src/automap.plugin.ts
This PR update's automap's defaultTargetSheet return value type to allow it to be an async function
Example usage:
```
listener.use(
automap({
accuracy: 'confident',
targetWorkbook: 'us_wb_123xyz',
defaultTargetSheet: async (fileName: string) => {
const { data: workbook }: Flatfile.WorkbookResponse =
await api.workbooks.get('us_wb_123xyz')
for (const {
config: { slug },
} of workbook.sheets) {
const regex = new RegExp(`${slug}.csv`)
if (fileName.match(regex)) {
return slug
}
}
},
})
)
```
=> feat: update automap's defaultTargetSheet

.changeset/hungry-pumpkins-explain.md, plugins/export-workbook/src/plugin.ts
This PR fixes the `@flatfile/plugin-export-workbook` plugin when deployed by writing to the tmp .xlsx file to `/tmp` dir. Lambdas only allow writing to `/tmp`.
Closes https://github.com/FlatFilers/support-triage/issues/926
=> fix: write tmp file to /tmp dir

.changeset/fair-lions-matter.md, package-lock.json, plugins/json-schema/tests/json-schema.e2e.spec.ts, plugins/record-hook/src/tests/bulkRecordHook.invalidData.e2e.spec.ts, plugins/record-hook/src/tests/bulkRecordHook.messages.e2e.spec.ts, plugins/record-hook/src/tests/bulkRecordHook.metadata.e2e.spec.ts, plugins/record-hook/src/tests/bulkRecordHook.nochange.e2e.spec.ts, plugins/record-hook/src/tests/bulkRecordHook.objectData.e2e.spec.ts, plugins/record-hook/src/tests/bulkRecordHook.simpleData.e2e.spec.ts, plugins/record-hook/src/tests/bulkRecordHook.throwError.e2e.spec.ts, plugins/record-hook/src/tests/recordHook.invalidData.e2e.spec.ts, plugins/record-hook/src/tests/recordHook.messages.e2e.spec.ts, plugins/record-hook/src/tests/recordHook.metadata.e2e.spec.ts, plugins/record-hook/src/tests/recordHook.objectData.e2e.spec.ts, plugins/record-hook/src/tests/recordHook.simpleData.e2e.spec.ts, plugins/record-hook/src/tests/recordHook.throwError.e2e.spec.ts, plugins/xlsx-extractor/package.json, plugins/xlsx-extractor/src/index.ts, plugins/xlsx-extractor/src/parser.ts, plugins/zip-extractor/src/zip.extractor.e2e.spec.ts, utils/extractor/src/index.ts
This PR fixes several issues related to large Excel file extractions. Previously the SheetJS library would quietly fail when attempting to parse large files. This release turns SheetJS's logging and listens for the ERR_STRING_TOO_LONG which indicates the file is too large to parse. When this occurs, the plugin will now throw an error with a message indicating the file is too large.
Additionally, a bug was fixed where the extraction job was not being immediately acknowledged. This resulted in a message indicating that `no listener has been configured to respond to it`. This has been fixed and the extraction job will now be acknowledged immediately.
A new `dateNF` option has been added to the plugin. This option allows you to specify the date format that should be used when parsing dates …
=> fix: large XLSX file handling

plugins/webhook-egress/src/webhook.egress.spec.ts
The latest version of `@flatfile/api` uses `fetch` which is also used by the webhook-egress plugin and thus cannot blanket mock fetch calls. This PR fixes the test to only mock certain fetch calls.
=> fix: webhook egress tests

.changeset/twenty-coins-complain.md, plugins/xml-extractor/src/parser.ts
This PR is a XML extractor bug fix for `Extractor error: Cannot use 'in' operator to search for '_attributes' in null`
Closes https://github.com/FlatFilers/support-triage/issues/937
=> fix: XML extractor bug fix

.changeset/fresh-humans-prove.md, plugins/webhook-egress/src/webhook.egress.spec.ts, utils/common/src/process.records.spec.ts, utils/common/src/process.records.ts, utils/response-rejection/src/index.ts
@flatfile/util-common: This release provides additional record request options such as "filter" and passes the current pageNumber to the cb function. Additionally the cb will be called when no records are found for any wrap-up the cb needs to make.
@flatfile/util-response-rejection: Since @flatfile/util-common now calls the cb when no records are found, this release updates @flatfile/util-response-rejection to check for records before processing.
=> feat: processRecords update

.github/workflows/lint.yml, .github/workflows/test.yml
This PR disables the `test` and `lint` workflows on the `changeset-release/main` branch.
=> feat: disable test & lint on changeset branch

.changeset/large-pigs-sleep.md, plugins/autocast/src/autocast.plugin.spec.ts, plugins/autocast/src/autocast.plugin.ts
Closes https://github.com/FlatFilers/support-triage/issues/1060
Create a sheet with a field of type `string` and insert an integer value. The autocast plugin will cast it to a string.
Since it is possible to insert a number or boolean into a field of type `string`, this release adds cast-to-string functionality to the autocast plugin.
=> feat: cast to string

.changeset/popular-pumas-fry.md, package-lock.json, plugins/export-workbook/src/index.ts, plugins/export-workbook/src/plugin.ts
Closes https://github.com/FlatFilers/support-triage/issues/1053
Create a sheet with a name containing a special character, then download the workbook. It should strip the special character from the name.
Excel does not support certain characters in sheet names due to its file format and system compatibility requirements. Here are the characters that are not allowed in Excel sheet names:
* Colon `:`
* Forward slash `/`
* Backslash `\`
* Question mark `?`
* Asterisk `*`
* Square brackets `[ ]`
* Greater than `>`
* Less than `<`
* Vertical bar `|`
* Double quotation mark `""`
Additionally, sheet names cannot begin or end with an apostrophe `'` and they must be under 31 characters in length.
This release strips invalid characters from the sheet name.
=> fix: excel worksheet names

.changeset/polite-steaks-tease.md, plugins/dxp-configure/src/index.ts
This takes the workbook passed along to the dxpConfigure plugin and adds it as the Primary Workbook ID to the Space. You can optionally set this to be false if you are adding multiple workbooks to the space with the plugin with the optional param `isPrimaryWorkbook`:
```ts
import { WorkbookOne } from "./workbook1";
import { WorkbookTwo } from "./workbook2";
export default function (listener: FlatfileListener) {
listener.use(dxpConfigure( WorkbookOne )
listener.use(dxpConfigure( WorkbookTwo, { isPrimaryWorkbook: false })
}
```
Check to make sure the created workbook is set on the Space as the Primary Workbook Id.
=> feat: update space with primary workbook id

.changeset/rich-carrots-hope.md, plugins/xlsx-extractor/src/parser.ts
This release fixes a bug in @flatfile/plugin-excel-extractor when using the explicitHeaders header detection algorithm.
Extraction should not error when using the `explicitHeaders` algorithm
```
listener.use(
ExcelExtractor({
headerDetectionOptions: {
algorithm: 'explicitHeaders',
headers: ['fiRsT NamE', 'LaSt nAme', 'emAil'],
},
})
)
```
=> fix: excel extractor header detection bug

turbo.json
Remove `"dependsOn": ["^build"]` from turbo test config since GH workflow runs `build` prior to running `test`
=> chore: remove build from test workflow

package-lock.json, plugins/autocast/package.json, plugins/autocast/src/autocast.plugin.ts, plugins/constraints/src/external.sheet.constraint.ts, plugins/record-hook/package.json, plugins/record-hook/src/record.translator.ts
This PR adds support for the `string-list` and `enum-list` field types.
Record hook:
```
listener.use(
recordHook('fieldTypes', (record: FlatfileRecord) => {
const colors = record.get('enum-list') as string[]
console.log({ colors })
if (colors.includes('green')) {
record.addWarning('enum-list', 'Green is questionable', 'green')
}
if (colors.includes('pink')) {
record.addInfo('enum-list', 'Pink is yayaay', 'pink')
}
if (colors.includes('blue')) {
record.addError('enum-list', 'Blue is naaay', 'blue')
}
const names = record.get('strings') as any[]
console.log({ names })
names?.forEach((name) => {
if (!isNaN(Number(name))) {
record.addWarning('strings', `${name} is a number`, name)
}
})
return record
})
)
```
Sheet config:
```
{
name: 'Field Types',
slug: 'fieldTypes',
fields: [
{
key: …
```
=> feat: support list fields

.changeset/large-impalas-do.md, plugins/job-handler/src/job.handler.ts
This PR changes the jobHandler to start the job progress at 0% rather than 10%.
=> fix: jobHandler starting progress 10% -> 0%

.changeset/unlucky-stingrays-lie.md, package-lock.json, plugins/dedupe/README.md, plugins/dedupe/src/dedupe.plugin.ts
This PR provides a more instructive error message when the dedupe plugin is miscalled from a workbook-level action instead of a sheet-level action.
=> feat: provide a more instructive error message when miscalled from a workbook-level action

.changeset/few-pots-move.md, .changeset/four-drinks-pump.md, package-lock.json, plugins/delimiter-extractor/src/parser.spec.ts, plugins/delimiter-extractor/src/parser.ts, plugins/xlsx-extractor/src/parser.spec.ts, plugins/xlsx-extractor/src/parser.ts, utils/extractor/src/index.ts
This removes the check for '*' for if the field should be required or not. Source sheets shouldn't be required
Upload an xlsx file with field name that has a * in it. The produces sheet.config.fields shouldnt have a constraint=required.
=> Removed field.constraint.required from extractors.

.github/workflows/changesets.yml, .github/workflows/cl-create.yml, .github/workflows/lint.yml, .github/workflows/test.yml, package-lock.json, package.json
=> Trigger on release published, remove auth from other actions

.changeset/sharp-wasps-happen.md, utils/extractor/src/index.ts
We changed how we generate column keys from the extracted file to prevent name collisions after further normalization.
=> fix: normalize extracted column keys

.changeset/fuzzy-foxes-guess.md, package-lock.json, plugins/delimiter-extractor/package.json, plugins/json-extractor/package.json, plugins/xlsx-extractor/package.json, plugins/xml-extractor/package.json
=> feat: update extractors to use the latest @flatfile/util-extractor@2.1.0

.changeset/plenty-singers-collect.md, flatfilers/sandbox/src/index.ts, utils/response-rejection/src/index.ts
This PR closes https://github.com/FlatFilers/support-triage/issues/1317.
When the response rejection utility is used in a listener that also has a recordHook and is configured with `deleteSubmitted: false`, a status field is added to the sheet to indicate with records are submitted vs rejected. When this field is updated it triggers the recordHook to run, which in turn wipes out any messages set by the response rejection utility.
To by-pass this, this PR makes two `api.records.update` calls with a short timeout between them. The first call updates the status field values (triggering the recordHook). The second call only updates the message. The short timeout ensures that the second call happens after the recordHook has run.
Test listener:
```
import type { FlatfileListener } from …
```
=> fix: response rejection

.changeset/short-apples-flash.md, plugins/xlsx-extractor/src/parser.ts
Fixes an issue where the presence of empty columns would shift the extracted cell values into other columns. While we remove null values for the purpose of header detection, we need to use the original data when constructing the actual headers.
An xlsx file with an empty column between filled columns should have the filled columns extracted correctly.
=> fix: null header extraction

.changeset/purple-lizards-cross.md, .github/workflows/test.yml, package-lock.json, package.json, test/toBePendingMatcher.ts, test/unit.cleanup.js, utils/testing/package.json, utils/testing/src/test.listener.spec.ts, utils/testing/src/test.listener.ts
Fixed bug where `waitFor` promise was being fulfilled immediately. Changed `invocations` to store a log of FlatfileEvents and `invocationWatchers` to be compatible with the existing `matchEvent` method on Flatfile Listeners. Also exposed `invocationWatchers` to the public API.
=> Prevent `waitFor` from fulfilling early in util/testing

.changeset/famous-pans-call.md, plugins/view-mapped/CHANGELOG.md
=> chore: release view mapped

.changeset/wise-zoos-smoke.md, plugins/xlsx-extractor/src/utils.ts, utils/extractor/src/index.ts
This PR closes https://github.com/FlatFilers/support-triage/issues/1583
For testing, create an excel sheet that has non-string values (date/integer) formatted as the appropriate non-string type in the header row. Uploading the file should not fail file extraction. This PR converts those non-string values to string.
Listener:
```
import type { FlatfileListener } from '@flatfile/listener'
import { ExcelExtractor } from '@flatfile/plugin-xlsx-extractor'
export default async function (listener: FlatfileListener) {
listener.use(
ExcelExtractor({
rawNumbers: true,
raw: true,
})
)
}
```
=> fix:non-string values

.changeset/lazy-trees-burn.md, convert/what3words/package.json, convert/what3words/src/index.ts, package-lock.json, plugins/delimiter-extractor/src/parser.ts
This release fixes an async bug
Import multiple what3words from a file. All records should update.
=> fix: async issue

.changeset/poor-starfishes-nail.md, package-lock.json, plugins/automap/package.json, plugins/automap/src/automap.plugin.ts, plugins/automap/src/automap.service.ts
This PR removes the remeda dependency & adds the `disableFileNameUpdate` option
Using the provided listener, upload the provided file. Ensure that the file name does not change and the file's data is mapped to the `getting-started` workbook.
[getting-started.csv](https://github.com/user-attachments/files/17382988/getting-started.csv)
```
import type { FlatfileEvent, FlatfileListener } from '@flatfile/listener'
import { automap } from '@flatfile/plugin-automap'
import { configureSpace } from '@flatfile/plugin-space-configure'
export default function (listener: FlatfileListener) {
const matchFilename = /(?:^|.*\s)getting-started\.csv(?:\s.*|$)/
listener.use(
automap({
accuracy: 'confident',
defaultTargetSheet: 'getting-started',
matchFilename,
disableFileNameUpdate: true,
onFailure: (event: …
```
=> feat: remove remeda & add `disableFileNameUpdate` option

.changeset/four-peas-change.md, package-lock.json, validate/date/README.md, validate/date/src/validate.date.plugin.spec.ts, validate/number/README.MD, validate/number/src/validate.number.plugin.ts
=> feat: fix some Readmes

.changeset/eleven-badgers-shout.md, flatfilers/sandbox/src/index.ts, package-lock.json, plugins/graphql-schema/src/index.ts, plugins/json-schema/src/index.ts, plugins/json-schema/src/setup.factory.ts, plugins/merge-connection/package.json, plugins/merge-connection/src/create.workbook.ts, plugins/openapi-schema/src/index.ts, plugins/openapi-schema/src/setup.factory.ts, plugins/sql-ddl-converter/src/index.ts, plugins/sql-ddl-converter/src/setup.factory.ts, plugins/yaml-schema/src/index.ts, plugins/yaml-schema/src/setup.factory.ts
This PR fixes an async/await bug.
Deploy the listener in `flatfiler/sandbox`, create a new space. The deployed listener should configure a space.
=> fix: async/await bug

.changeset/eighty-panthers-collect.md, extract/html-table/package.json, extract/markdown/package.json, package-lock.json, plugins/json-extractor/package.json, plugins/openapi-schema/src/setup.factory.openapi.spec.ts, plugins/xml-extractor/package.json
=> chore: dep update

.changeset/gentle-bobcats-laugh.md, package-lock.json, plugins/json-schema/src/setup.factory.spec.ts, plugins/json-schema/src/setup.factory.ts, plugins/openapi-schema/src/setup.factory.ts, plugins/yaml-schema/src/setup.factory.spec.ts
=> JSON array -> Flatfile string-list

.changeset/green-bobcats-brake.md
This is the changeset for https://github.com/FlatFilers/flatfile-plugins/pull/709
=> Changeset for PR #709

.changeset/proud-snails-jam.md, plugins/automap/src/automap.service.ts
This PR adds more logging to the automap plugin
Closes https://github.com/FlatFilers/support-triage/issues/1704
=> chore: better logging in automap plugin

.changeset/dull-apes-deny.md, plugins/view-mapped/src/view-mapped.ts
This PR fixes a bug in the view-mapped plugin when multiple sheets have fields with the same key by limiting the view-mapped update to the sheet being mapped. Additionally, the view-mapped plugin now only runs when the `trackChanges` setting in the workbook is enabled to prevent a race condition where the view-mapped plugin runs before hooks have completed.
Closes https://github.com/FlatFilers/support-triage/issues/1696
=> fix: view-mapped plugin restrict to mapped sheet

.changeset/spotty-cougars-smash.md, flatfilers/sandbox/package.json, package-lock.json, plugins/xlsx-extractor/package.json, plugins/xlsx-extractor/src/parser.ts, plugins/xlsx-extractor/src/utils.spec.ts, plugins/xlsx-extractor/src/utils.ts
Closes: https://github.com/FlatFilers/support-triage/issues/1699
The PR closes https://github.com/FlatFilers/support-triage/issues/1699 by removing the trailing null header cells after the last non-null header cell.
=> fix: issue 1699

.changeset/five-carrots-explain.md, plugins/record-hook/src/RecordHook.ts, plugins/record-hook/src/record.hook.plugin.ts
This PR fixes the issue https://github.com/FlatFilers/configurator/issues/20
Remove the `?` to make the `event` parameter non optional at `BulkRecordHook` function since we always have this information
The project should work the same way as before
=> Mark the event as non optional for BulkRecordHook

.changeset/bright-ties-promise.md, package-lock.json, plugins/view-mapped/src/view-mapped.ts, utils/extractor/README.md
This release adds a brief delay to the view-mapped plugin prior to updating the workbook's fields. Additionally fixes a dead link in util-extractor.
=> add brief delay to view-mapped plugin

.changeset/eleven-cameras-pretend.md, package-lock.json, plugins/space-configure-from-template/package.json, plugins/space-configure-from-template/src/space.configure.from.template.ts
- Get space template by appid and use the namespace from the space template instead of from the app
- Getting the app requires account level access, but agents only have environment level access
- Also fixed a bug with space update request body
- Bug fixes for space-configure-from-template plugin
- No longer relies on app access for namespace information
- Fixed a space update request body bug
=> feat: Use SpaceTemplate info for Namespace

.changeset/tricky-plants-kiss.md, flatfilers/sandbox/src/index.ts, package-lock.json, plugins/xlsx-extractor/src/parser.ts, utils/extractor/src/index.ts
Added translation keys for the excel extractor and extractor util
When this is run with the accompanying Platform PR, the excel extraction process should be unchanged and the correct messages should be seen instead of translation keys.
=> adding translations to excel extractor and extractor plugin

.changeset/warm-chairs-bake.md, flatfilers/sandbox/src/index.ts, flatfilers/sandbox/src/sheets/contacts.ts, plugins/xlsx-extractor/src/header.detection.ts
Fixes https://github.com/FlatFilers/support-triage/issues/1784
=> fix: issue when `raw` or `rawNumbers` options are enabled

.changeset/few-sloths-clean.md, flatfilers/sandbox/src/index.ts, package-lock.json, plugins/space-configure/src/index.ts, plugins/space-configure/src/utils/data.checklist.ts
This PR introduces a data checklist utility that can be used to create a Data Checklist Document.
Run the sandbox listener and create a space.
=> feat: data checklist

.changeset/violet-flies-warn.md, plugins/view-mapped/src/view-mapped.ts
This PR fixes an issue computing records by running the view-mapped job at the sheet level
=> fix: view mapped plugin

.changeset/cuddly-moles-rule.md, flatfilers/sandbox/src/index.ts, plugins/space-configure/src/data.checklist.ts, plugins/space-configure/src/index.ts, plugins/space-configure/src/utils/data.checklist.ts
This release creates a `dataChecklistPlugin` for ease of use when not using the `configureSpace` plugin or if you want to keep the Data Checklist Document updated when the workbooks/sheets change.
Just build, run the sandbox listener, and create a space.
=> feat: dataChecklist plugin

.changeset/healthy-donuts-invite.md, plugins/constraints/src/external.constraint.ts, plugins/constraints/src/external.sheet.constraint.ts
This adds support for async `cb()`
=> fix: async issues

.changeset/two-queens-happen.md, package-lock.json, plugins/view-mapped/src/view-mapped.ts
=> viewMapped retain required fields option

.changeset/bright-ducks-turn.md, plugins/webhook-event-forwarder/README.md, plugins/webhook-event-forwarder/package.json, plugins/webhook-event-forwarder/src/forward-webhook.e2e.spec.ts, plugins/webhook-event-forwarder/src/forward.webhook.ts
This PR add documentation to the webhook-event-forwarder plugin
=> webhook-event-forwarder docs

.changeset/fluffy-pillows-call.md, plugins/export-workbook/README.md, plugins/export-workbook/src/index.ts, plugins/export-workbook/src/options.ts, plugins/export-workbook/src/plugin.ts, plugins/export-workbook/src/utils.spec.ts, plugins/export-workbook/src/utils.ts
New options were added to the `export-workbook` plugin options:
- `columnNameTransformer` is a callback function enabling users to transform column names before exporting workbook. The callback takes a column name and slug name and returns a string. 
- `sheetOptions` is map of slug name to `SheetOptions` object with these props:
- `origin`  the starting point of the sheet (can either be a row number or full column, row coordinate)
- `skipColumnHeaders` optionally not include column headers. I know its not relevant for our use case, but could be worth while for someone.
This was tested in the plugin sandbox. 
A second sheet was added:
```
export const companies: Flatfile.SheetConfig = {
name: 'Companies',
slug: 'companies',
fields: [
{
key: 'name',
type: 'string',
label: 'Name', …
```
=> Features added to export-workbook plugin

.changeset/pink-apricots-double.md, package-lock.json, utils/extractor/src/index.ts
The smart extractor feature is handling excel files when enabled. This circumvents the excel extractor from triggering if smart extractor is enabled.
Add smart extractor entitlement. Upload an excel file. The plugin shouldn't create a job for excel extraction
=> Added logic to not create excel job if smart extractor is enabled

.changeset/blue-mayflies-change.md, flatfilers/sandbox/src/index.ts, plugins/export-workbook/README.md, plugins/export-workbook/src/options.ts, plugins/export-workbook/src/plugin.ts
adds an option to the plugin that allows the user to choose to omit messages on records from the generated file
Test the following scenarios: 
`  listener.use(exportWorkbookPlugin())` - no option specified - this should download a file with messages on cells
`  listener.use(exportWorkbookPlugin({excludeMessages: true}))` - option set to true - this should download a file with no record hook messages on cells
`  listener.use(exportWorkbookPlugin({excludeMessages: false}))` - option set to false - this should download a file with messages on cells
=> added option to exclude messages from the downloaded workbook

.changeset/nine-bags-pump.md, plugins/export-workbook/src/options.ts, plugins/export-workbook/src/plugin.ts
This PR adds an option to provided a file name
```
listener.use(
exportWorkbookPlugin({
filename: "custom-file-name",
}),
);
```
=> export workbook filename option
