.changeset/mean-deers-tap.md, plugins/record-hook/package.json, plugins/record-hook/src/RecordHook.ts, plugins/record-hook/src/index.ts
=> feat: update RecordHook

.changeset/swift-shrimps-hug.md, plugins/record-hook/src/RecordHook.ts, pnpm-lock.yaml
Make sure to pull the latest `records` from cache without stripping messages
=> fix: Messages Being Stripped from Records

.env.defaults, CONTRIBUTING.md, README.md, jest.config.js, package-lock.json, package.json, plugins/record-hook/package.json, plugins/record-hook/src/RecordHook.ts, plugins/record-hook/src/e2e.spec.ts, testing/setup-tests.js, testing/test.helpers.ts, testing/test.listener.ts, tsconfig.json
grungy e2e test of a plugin, improvements to be done. And yes these keys are safe to commit to code.
=> feat: e2e testing

.changeset/lazy-ties-scream.md, package-lock.json, plugins/xlsx-extractor/README.md, plugins/xlsx-extractor/src/abstract.extractor.ts, plugins/xlsx-extractor/src/excel.extractor.ts, plugins/xlsx-extractor/src/index.ts, plugins/xlsx-extractor/src/xlsx.extractor.plugin.ts
This PR seeks to tell end users status while the XLXS extractor is working and where it failed, when it fails. It uses a custom job now instead of a built-in job.
The UI will be updated to show this in the Files area.
if (job.status = "created" or "ready")
0% Waiting (progress + "%" + " " + job.info)
if (job.status = "executing")
10% Downloading (progress + "%" + " " + job.info)
30% Parsing Sheets (progress + "%" + " " + job.info)
50% Creating Workbook (progress + "%" + " " + job.info)
80% Adding records to Sheets (progress + "%" + " " + job.info)
if (job.status = "failed")
Extraction failed during ___. (job.info)
if (job.status = "complete")
Extraction complete (job.info)
=> feat: readme updates, improvements to extractor

.changeset/popular-beers-smash.md, package-lock.json, plugins/record-hook/package.json, plugins/record-hook/src/RecordHook.ts, plugins/record-hook/src/e2e.spec.ts, plugins/record-hook/src/index.ts
=> feat: Make recordHook use event.update()

.github/workflows/lint.yml, .github/workflows/test.yml
"you may only define one of `branches` and `branches-ignore` for a single event"
=> fix: workflows

.changeset/green-radios-watch.md, package-lock.json, plugins/autocast/README.md, plugins/autocast/package.json, plugins/autocast/src/autocast.plugin.spec.ts, plugins/autocast/src/autocast.plugin.ts, plugins/autocast/src/index.ts, plugins/record-hook/src/RecordHook.ts, utils/common/src/async.batch.spec.ts, utils/common/src/async.batch.ts
This PR introduces the autocast plugin. This Guides PR describe usage: https://github.com/FlatFilers/Guides/pull/737
=> feat: autocast implementation

.changeset/brave-files-obey.md, package-lock.json, plugins/webhook-egress/src/webhook.egress.ts, utils/response-rejection/src/index.ts
Related Guides PR: https://github.com/FlatFilers/Guides/pull/791
=> feat: update response rejection message

.changeset/tricky-ants-flow.md, utils/extractor/src/index.ts
Closes https://github.com/FlatFilers/flatfile-plugins/issues/203
=> feat: job progress

plugins/record-hook/src/RecordHook.ts
Closes: https://github.com/FlatFilers/support-triage/issues/663
=> fix: bulkRecordHook overwriting messages from recordHook

.changeset/lovely-cobras-hunt.md, package-lock.json, plugins/automap/src/automap.plugin.e2e.spec.ts, plugins/dedupe/src/index.ts, plugins/dxp-configure/src/index.ts, plugins/export-worbook/src/index.ts, plugins/record-hook/src/index.spec.ts, plugins/record-hook/src/record.hook.plugin.ts, plugins/space-configure/src/space.configure.ts, plugins/webhook-egress/src/webhook.egress.ts, utils/common/src/async.batch.ts, utils/extractor/src/index.ts
Related Guide PR: https://github.com/FlatFilers/Guides/pull/797
=> fix: proper awaiting & better job progress

.changeset/tricky-eagles-explain.md, package-lock.json, plugins/xlsx-extractor/package.json
This PR updates the XLSX dependency version
=> chore: update xlsx dependency version

.changeset/short-ties-whisper.md, plugins/merge-connection/src/index.ts
This PR fixes a job tick() bug.
=> Fix connect merge

.changeset/famous-buckets-drive.md, package-lock.json, plugins/record-hook/src/RecordHook.ts, plugins/record-hook/src/record.translater.ts, utils/extractor/src/index.ts
Closes: https://github.com/FlatFilers/Guides/issues/794
=> chore: change import method

.changeset/modern-monkeys-tan.md, package-lock.json, plugins/export-workbook/src/plugin.ts, plugins/job-handler/src/job.handler.spec.ts
This PR fixes a couple bugs:
- add option flag to export recordId
- fix column pattern generator
- pass column count to generator per sheet
- properly fail jobs on error
- delete files after upload
=> feat: export-workbook bug fixes

.changeset/rare-parents-swim.md, plugins/delimiter-extractor/src/index.ts, plugins/json-extractor/src/index.ts, plugins/xlsx-extractor/src/index.ts, plugins/xml-extractor/src/index.ts
This PR exports each extractor's parser.
=> feat: export each extractor's parser

.changeset/curly-cars-relate.md, package-lock.json, plugins/record-hook/src/RecordHook.ts
This PR fixes a bug on record comparison
=> fix: record comparison

.changeset/cyan-oranges-care.md, package-lock.json, plugins/json-schema/src/setup.factory.ts
This PR fixes the changeset on PR https://github.com/FlatFilers/flatfile-plugins/pull/294 and includes a minor bug fix
=> fix: JSON schema plugin changeset

.changeset/small-moles-judge.md, package-lock.json, plugins/job-handler/src/job.handler.ts, plugins/merge-connection/src/index.ts, plugins/space-configure/src/space.configure.ts, utils/extractor/src/index.ts
This PR makes the `progress` param required and fixes a bug when no `info` param is provided. Closes https://github.com/FlatFilers/support-triage/issues/770
Guide update: https://github.com/FlatFilers/Guides/compare/feat/update-tick-params?expand=1
=> fix: tick() params

.changeset/plenty-fishes-sleep.md, jest.config.js, package-lock.json, plugins/json-extractor/package.json, plugins/json-extractor/src/parser.spec.ts, plugins/json-extractor/src/parser.ts
This PR introduced support for nested objects and array to the JSON Extractor by flattening objects and stringifying arrays.
=> feat/add nested object & array support to JSON extractor

.changeset/itchy-beers-cheat.md, package-lock.json, plugins/json-schema/src/index.ts, plugins/json-schema/src/setup.factory.ts, plugins/json-schema/tests/json-schema.e2e.spec.ts
This PR improves how JSON schema is provided to the plugin. Schema can now be provided via an object, url, or use a function for a custom retrieval process.
```
listener.use(
configureSpaceWithJsonSchema({
workbooks: [
{
name: 'JSON Schema Workbook',
sheets: [
{ // Pass url to schema
source: 'http://localhost:1234/schema/customer',
name: 'Custom Sheet Name - Customer',
},
{ // Use function for custom retrieval process
source: async () =>
await fetchExternalReference(
'http://localhost:1234/schema/product'
),
name: 'Custom Sheet Name - Product',
},
{ // Pass schema object
source: {
$id: 'https://localhost:3000/json',
description:
'A basic set of JSON Schema to test data type conversions simply',
type: 'object',
title: 'ExampleData',
properties: {
stringColumn: {
description: 'A column for …
```
=> feat: json schema refactor

.changeset/ninety-owls-move.md, jest.config.js, package-lock.json, plugins/json-extractor/package.json, plugins/json-extractor/ref/test-basic.json, plugins/json-extractor/rollup.config.mjs, plugins/json-extractor/src/parser.spec.ts, plugins/json-extractor/src/parser.ts
This PR does a minor refactoring of the json extractor to remove the `flat` dep and switch the build tool to rollup
=> feat: refactor json extractor

.changeset/red-fireants-hammer.md, package-lock.json, utils/response-rejection/src/index.ts
Fixes displaying the next option and corrects the button's title
=> fix:rejection plugin job next button title

package-lock.json, package.json, plugins/record-hook/package.json, plugins/record-hook/rollup.config.mjs
Reduces dist/ 12.2mb -> 37kb
Closes https://github.com/FlatFilers/flatfile-plugins/issues/362
=> feat: expand recordHook rollup config

.changeset/serious-islands-wait.md, plugins/space-configure/src/space.configure.ts, plugins/sql-ddl-converter/package.json
This PR adds documents in the Setup object, allowing document config to be more easily created.
Example usage:
```
listener.use(
configureSpace(
{
workbooks: [
{
name: 'Playground',
sheets: [
{
name: 'Contacts',
slug: 'contacts',
fields: [
{
key: 'name',
type: 'string',
label: 'Name',
constraints: [{ type: 'required' }],
},
{
key: 'email',
type: 'string',
label: 'Email',
constraints: [{ type: 'unique' }],
},
],
actions: [
{
operation: 'duplicateSheet',
mode: 'foreground',
label: 'Duplicate',
description: 'Duplicate this sheet.',
primary: true,
},
],
},
],
actions: [
{
operation: 'submitActionFg',
mode: 'foreground',
label: 'Submit data',
type: 'string',
description: 'Submit this data to a webhook.',
primary: true,
},
{
operation: 'downloadWorkbook',
mode: 'foreground',
label: 'Download …
```
=> feat: accept documents in setup object

.changeset/friendly-geckos-doubt.md, package-lock.json, plugins/record-hook/src/RecordHook.ts, plugins/record-hook/src/tests/bulkRecordHook.objectData.e2e.spec.ts, plugins/record-hook/src/tests/recordHook.objectData.e2e.spec.ts
This PR fixes a bug that caused the recordHook to fetch data on every run.
=> fix: optimize data fetch

.changeset/poor-dolphins-dance.md, .gitignore, package-lock.json, plugins/constraints/CHANGELOG.md, plugins/constraints/README.md, plugins/constraints/package.json, plugins/constraints/rollup.config.mjs, plugins/constraints/src/external.constraint.e2e.spec.ts, plugins/constraints/src/external.constraint.ts, plugins/constraints/src/get.constraints.ts, plugins/constraints/src/index.ts, utils/testing/src/test.helpers.ts
Introduces the external constraints plugin
=> feat: external constraints plugin

.changeset/tasty-berries-add.md, plugins/autocast/src/autocast.plugin.spec.ts, plugins/autocast/src/autocast.plugin.ts
This PR upgrades the messaging when a value is cast. It also fixes a bug when the autocast plugin is used concurrently with recordHooks.
Closes https://github.com/FlatFilers/support-triage/issues/957
Closes https://github.com/FlatFilers/support-triage/issues/988
=> feat: refactor autocast

.changeset/breezy-ravens-destroy.md, .changeset/dirty-beans-bake.md, package-lock.json, package.json, plugins/autocast/package.json, plugins/automap/package.json, plugins/constraints/package.json, plugins/dedupe/package.json, plugins/dxp-configure/package.json, plugins/export-workbook/package.json, plugins/job-handler/package.json, plugins/json-extractor/package.json, plugins/json-schema/package.json, plugins/merge-connection/package.json, plugins/openapi-schema/package.json, plugins/pdf-extractor/package.json, plugins/psv-extractor/package.json, plugins/record-hook/package.json, plugins/record-hook/rollup.config.mjs, plugins/space-configure/package.json, plugins/webhook-egress/package.json, plugins/webhook-event-forwarder/package.json, plugins/yaml-schema/package.json, plugins/zip-extractor/package.json, utils/common/package.json, utils/extractor/package.json, utils/fetch-schema/package.json, utils/file-buffer/package.json, utils/response-rejection/package.json, utils/testing/package.json
- Updates all plugins to the latest `@flatfile/listener@^1.0.0` package
- Updates the `@flatfile/plugin-record-hook` to include external packages in build
- Updates browser package.json to exports instead.
=> feat: adjust record hook builds

.changeset/sweet-spoons-explain.md, package-lock.json, plugins/constraints/rollup.config.mjs
This PR fixes the constraints plugin's build.
Closes: https://github.com/FlatFilers/support-triage/issues/1026
=> fix: constraints build

.changeset/cyan-toys-switch.md
Changeset for https://github.com/FlatFilers/flatfile-plugins/pull/410
=> Missed changeset

.changeset/fast-suns-behave.md, plugins/autocast/src/autocast.plugin.spec.ts, plugins/autocast/src/autocast.plugin.ts
This PR makes the autocast error message friendlier for non-technical users.
=> feat: simplify autocast error message

.changeset/happy-lies-fry.md, plugins/export-workbook/src/index.ts, plugins/export-workbook/src/plugin.ts
Previous release broke backwards compatibility. This PR restores backward compatibility.
=> fix: backwards compatibility

.changeset/chilled-rabbits-invite.md, plugins/foreign-db-extractor/src/database.poll.status.ts, plugins/foreign-db-extractor/src/database.user.ts, plugins/foreign-db-extractor/src/index.ts, plugins/foreign-db-extractor/src/sheets.generator.ts
This PR improves the error handling in the `@flatfile/plugin-foreign-db-extractor` plugin, correctly set the file status on job completion, and polls for a DB user since it may take time for the restored DB to become available.
On staging, run plugin, upload a Standard Edition .bak file. It will successfully extract.
=> feat: improve error handling and DB user retrieval

.changeset/spicy-deers-scream.md, plugins/automap/README.md, plugins/automap/package.json
Updated description, URL, and keywords and readme content for `@flatfile/plugin-automap` plugin
=> feat: update readme and keywords for automap plugin

.changeset/beige-hornets-fry.md, plugins/dxp-configure/README.md, plugins/dxp-configure/package.json
=> feat: update readme and keywords for dxp-config plugin

.changeset/rude-donuts-crash.md, plugins/job-handler/README.md, plugins/job-handler/package.json, plugins/space-configure/README.md, plugins/space-configure/package.json
Update package keywords and readme for job-handler and space-configure plugins
Validate readme content
=> feat: update readme and keywords for core plugins

.changeset/mighty-crabs-worry.md, utils/extractor/README.md, utils/extractor/package.json, utils/file-buffer/README.md, utils/file-buffer/package.json, utils/response-rejection/README.md, utils/response-rejection/package.json
Add readme content and package keywords for all utils
Validate readme content
=> feat: update readme content and package keywords for utils

.changeset/little-ghosts-love.md, utils/response-rejection/src/index.ts
Closes https://github.com/FlatFilers/support-triage/issues/1251
=> fix: deletion of valid records in response-rejection util

.changeset/beige-ravens-learn.md, .gitignore, plugins/dedupe/README.md, plugins/dedupe/src/dedupe.plugin.ts
=> Update dedupe's README example

.changeset/angry-socks-exercise.md, plugins/record-hook/src/record.translator.ts
Changeset for https://github.com/FlatFilers/flatfile-plugins/pull/525
=> Changeset for PR 525

.changeset/sixty-needles-greet.md, package-lock.json, plugins/job-handler/src/job.handler.ts
This PR fixes a bug when an invalid job outcome is returned by the callback.
=> fix: jobHandler error handling

utils/extractor/src/index.ts
Fix finding if headerselection is enabled.
=> Update to entitlement name in find

.changeset/chilly-days-search.md, package-lock.json
=> updated changeset

package-lock.json, package.json
NA
Run an npm install without any creds.
=> Make changelog dep optional

.changeset/lazy-bananas-act.md, package-lock.json, plugins/delimiter-extractor/package.json, plugins/xlsx-extractor/package.json, plugins/xml-extractor/package.json
=> chore: Updated util extractor

.github/workflows/changesets.yml, .github/workflows/cl-create.yml
Updates github actions to use github app auth.
NA
I believe we'll have to merge and release an update to test.
=> Use github app auth

.github/scripts/getReviewers.js, .github/workflows/cl-create.yml, package-lock.json, package.json
=> Update to open pr from this side

.changeset/calm-ligers-remember.md, utils/extractor/src/index.ts
Auto enables the allowAdditionalFields on sheets when sourceEditor entitlement is on.
=> cascaded sourceEditor Entitlement to sheet Config Create

.github/workflows/cl-create.yml
=> Print reviewer to check, fix open pr step

.github/workflows/cl-create.yml
=> fix copy paste error

.github/scripts/getReviewers.js
=> Fix reviewers script output

package.json
=> chore: add /validators folder

.github/scripts/getReviewers.js
=> Remove stray console.log

.changeset/big-paws-deliver.md, .github/workflows/test.yml, package-lock.json, plugins/automap/src/automap.service.ts
Reverts back to the .every() from .some()
=> Reverted the some function to the every

.github/workflows/test.yml
=> feat: remove extra test

.changeset/wicked-seas-build.md, package-lock.json
=> chore: regen plugin's docs

.changeset/calm-planes-wait.md, plugins/record-hook/package.json
=> feat: update main in record hook plugin package.json

.changeset/famous-carrots-drive.md, package-lock.json, plugins/autocast/package.json, plugins/record-hook/package.json
- **feat: update to latest @flatfile/hooks**
- **chore: changeset**
=> feat: update `@flatfile/hooks`

.changeset/rich-dolphins-march.md, utils/common/package.json, utils/common/rollup.config.mjs
This PR adds a UMD build for the `@flatfile/utils-common` NPM package.
=> feat: umd build

plugins/constraints/package.json
=> Add keyword for docs build

.changeset/perfect-trees-poke.md
=> Add changeset

.changeset/five-clouds-hang.md, package-lock.json, plugins/webhook-egress/src/webhook.egress.ts
If a webhook returns status code 200 the webhook succeeds.
If the rest of the successful webhook response is not parseable user message is added.
=> Update webhook egress response handling

.changeset/good-garlics-rest.md, plugins/record-hook/src/RecordHook.ts, plugins/record-hook/src/record.translator.ts, plugins/record-hook/src/record.utils.ts
Closes https://github.com/FlatFilers/support-triage/issues/1764
=> fix: record diff-ing

.changeset/strong-guests-hunt.md, flatfilers/sandbox/src/index.ts, plugins/xlsx-extractor/src/parser.ts, utils/extractor/src/index.ts
This PR fixes an issue when a sheet contains no discernible content/headers.
=> fix: excel extractor no headers in sheet

.changeset/eleven-queens-promise.md, plugins/xlsx-extractor/package.json
=> Updated util version

.changeset/curvy-eyes-yell.md, package-lock.json, plugins/merge-connection/src/index.ts, plugins/webhook-egress/src/webhook.egress.e2e.spec.ts, plugins/webhook-event-forwarder/src/forward-webhook.e2e.spec.ts, plugins/webhook-event-forwarder/src/forward.webhook.ts
=> minor bug fixes

.changeset/bright-pears-divide.md, package-lock.json, utils/extractor/src/index.ts
- New Smart Extract Workflow handling. Removing check.
=> handling a different workflow for smart extract

.changeset/warm-monkeys-pretend.md, package-lock.json, plugins/space-configure-from-template/src/space.configure.from.template.ts
=> fix: add default obj for metadata

.changeset/quick-pianos-camp.md, plugins/pdf-extractor/src/plugin.ts
wait for full file to return before then uploading and extracting
=> fix race condition

.changeset/chilly-flowers-clean.md, plugins/xlsx-extractor/src/parser.ts, utils/common/src/all.records.ts, utils/extractor/src/index.ts
=> fix extractor key normalization

utils/common/src/normalize-sheet-config.spec.ts
=> Fixed tests
